### PR TITLE
web edits

### LINKED ISSUE #121: object oriented
more justification and (!!) analysis, why design decisions made and what you would change

### LINKED ISSUE #126: web tech
analysis of react as a tool, known issues (link to the GitHub issues / create new GitHub issues where possible) 

fix up those double bullet points (numbers and bullets) love you guys <3

### LINKED ISSUE #129: sprints
add the code implemented and links to that to go with each user story

### PR DESCRIPTION
**Pull request by Chris19138**

### CODE REVIEW

**Comment by Chris19138** [comment]
reviewed& reworded communication & added evaluation

**Comment by Chris19138** [comment]
added evaluation in object oriented design & web technologies in use

**Comment by Chris19138** [comment]
added to Sprints

**Review by amyconroy — APPROVED** [review]
great thank you! just edited typos (in my own work that i noticed too) 

won't merge so ollie can change, the one conflict might be with the work from ana that i merged (easy to fix)

**Pull request merged**
